import React, { useState } from 'react'
import Head from 'next/head'

import Navbar from '@/components/Navbar.js';
import Footer from '@/components/Footer.js';

function About() {
  return (
    <>

      <Head>
        <title>ABOUT|Jezh Technologies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous"/>
      </Head>



      <Navbar/>






{/* <section className="mb-4">


    <h2 className="h1-responsive font-weight-bold text-center my-4">Contact us</h2>

    <p className="text-white text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
        a matter of hours to help you.</p>

    <div className="row">

        
        <div className="col-md-9 mb-md-0 mb-5">
            <form id="contact-form" name="contact-form"  method="POST">

                
                <div className="row">

                    
                    <div className="">
                        <div className="md-form mb-0">
                            <input value={name} type="text" id="name" name="name" className="form-control" onChange={(e)=>{setName(e.target.value)}}/>
                            <label for="name" className="text-white">Your name</label>
                        </div>
                    </div>
                    

                    
                    <div className="">
                        <div className="md-form mb-0">
                            <input value={email} type="text" id="email" name="email" className="form-control"onChange={(e)=>{setEmail(e.target.value)}}/>
                            <label for="email" className="text-white">Your email</label>
                        </div>
                    </div>
                    

                </div>
                

                
                <div className="row">
                    <div className="col-md-12">
                        <div className="md-form mb-0">
                            <input value={Subject} type="text" id="subject" name="subject" className="form-control"onChange={(e)=>{setSubject(e.target.value)}}/>
                            <label for="subject" className="text-white">Subject</label>
                        </div>
                    </div>
                </div>
                

                
                <div className="row">

                    
                    <div className="col-md-12">

                        <div className="md-form">
                            <textarea value={message} onChange={(e)=>{setMessage(e.target.value)}} type="text" id="message" name="message" rows="2" className="form-control md-textarea"></textarea>
                            <label for="message" className='text-white'>Your message</label>
                        </div>

                    </div>
                </div>
                
             <center><button onClick={send} className='btn btn-primary' >send</button></center>
            </form>

            
   
      
</div>
    </div>

</section> */}

<Footer/>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</>
  )
}

export default About
