import React, { useState } from 'react'
import Head from 'next/head'
import axios from 'axios';
import Navbar from '@/components/Navbar.js';
import Footer from '@/components/Footer.js';

function Contact() {
    const [name,setName] = useState('')
    const [email,setEmail] = useState('')
    const [Subject,setSubject] = useState('')
    const [message,setMessage]= useState('')
    
    const send =async (e)=>{
        e.preventDefault();

        
      
        try {
          await axios.post('/api/mail', { name:name, email:email, message:message ,subject:Subject });
          console.log('Email sent successfully');
          // Reset the form or show a success message to the user
        } catch (error) {
          console.error('Error sending email:', error);
          // Handle and display the error to
      }
    }
  return (
    <>

      <Head>
        <title>Jezh Technologies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous"/>
      </Head>



      <Navbar/>



      <section>


      <div class="container py-3">

    <div class="px-lg-5 py-3  mb-4 bg-body-tertiary rounded-4">
      <div class="container-fluid">
        <div class="row align-items-md-stretch">
        <div class="col-md-8 d-flex align-items-center">
          <div class="">
          <h1 class="display-6 fw-bolder">Contact Us</h1>
        <p class="col-md-8 fs-5 fw-medium">For general queries, sales and partnerships please drop a email anytime and we will reach you.</p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start pt-2">
        <a class="btn bg-black text-white text-start btn-lg rounded-3 me-md-2" href="mailto:info@jezhtechnologies.com">
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-envelope-fill me-2 mb-1" viewBox="0 0 16 16">
  <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757Zm3.436-.586L16 11.801V4.697l-5.803 3.546Z"/>
</svg>
          <span className="fs-5 fw-semibold text-break">info@jezhtechnologies.com</span>
        </a>

          <a class="btn bg-success text-white btn-lg px-4 text-start text-decoration-none" data-action="open" data-phone="919385722102" data-message="Hello, I am interested in your service" href="https://web.whatsapp.com/send?phone=919385722102&amp;text=Hello, I am interested in your service" target="_blank">
          
          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-whatsapp me-2 mb-1" viewBox="0 0 16 16">
  <path d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z"/>
</svg>
            <span className="fs-5 fw-bold text-break text-white">+91-93857 22102</span>
          </a>
        </div>

        
          </div>
        </div>
        <div class="col-md-4">
          <div class="">
            <img className="img-fluid" src="https://uploads-ssl.webflow.com/6450b8115518edb92e39a41a/646f0e4ce7321b061e4a97f0_Contact%20us-cuate-p-800.png" alt="" width="500"/>
          </div>
        </div>
    </div>
      </div>
    </div>

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 bg-white rounded-4">
          <h1 className="fw-bolder">Office Location</h1>
          <p className="fs-4 fw-medium">Have an idea? Let's grab a coffee and make a revolution.</p>
          <address className="fs-4 fw-semibold">
    <strong>JEZH TECHNOLOGIES</strong><br/>
    Sri Sai Complex, Court Road,<br/>
    Vepamoodu Junction, Nagercoil,<br/>
    Kanyakumari, Tamil Nadu,<br/>
    India-629001.<br/>
    <abbr title="Phone">Phone:</abbr> 93857 22102 <br/>
    <abbr title="Phone">Landline:</abbr> 04652-288007

  </address>
          
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-3 bg-body-tertiary border rounded-3 ratio ratio-4x3">
        <iframe className="rounded-4 img-fluid" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d739.8872091509062!2d77.43067399307816!3d8.182330973528224!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3b04f1d9f6f28009%3A0xfbc653de52850d62!2sJabz%20Technologies%20Private%20Limited!5e1!3m2!1sen!2sin!4v1685065256487!5m2!1sen!2sin" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
      </div>
    </div>
  </div>








        {/* <div class="container px-lg-5 my-3 bg-white rounded-5">
    <div class="row align-items-center">
      <div class="col-lg-8">
        <h1 class="display-3 fw-bold text-black">Contact us</h1>
        <div class="badge bg-transparent text-wrap" >
        <p class="text-black lead fs-5 py-2">
For general queries, sales and partnerships please drop a email anytime and we will reach you.
</p>
        </div>


<div class="d-grid gap-2 d-md-flex justify-content-md-start">
<a className="btn btn-dark " href="">E-MAIL US</a>
<a className="btn btn-dark " align="left" href="">
<ul class="list-inline">
  <li class="list-inline-item">
  <span>WHATSAPP US ON</span>
    <br />
    <span>+91-94867 99358</span>
  </li>
  <li class="list-inline-item">
  <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-whatsapp" viewBox="0 0 16 16">
  <path d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z"/>
</svg>
  </li>

</ul>
</a>
        </div>

        
      </div>
      <div class="col-lg-4 p-0">
          <img class="rounded-lg-3 img-fluid" src="https://uploads-ssl.webflow.com/6450b8115518edb92e39a41a/646f0e4ce7321b061e4a97f0_Contact%20us-cuate-p-800.png" alt="" width="500"/>
      </div>
    </div>
  </div> */}




        </section>



{/* <section className="mb-4">


    <h2 className="h1-responsive font-weight-bold text-center my-4">Contact us</h2>

    <p className="text-white text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
        a matter of hours to help you.</p>

    <div className="row">

        
        <div className="col-md-9 mb-md-0 mb-5">
            <form id="contact-form" name="contact-form"  method="POST">

                
                <div className="row">

                    
                    <div className="">
                        <div className="md-form mb-0">
                            <input value={name} type="text" id="name" name="name" className="form-control" onChange={(e)=>{setName(e.target.value)}}/>
                            <label for="name" className="text-white">Your name</label>
                        </div>
                    </div>
                    

                    
                    <div className="">
                        <div className="md-form mb-0">
                            <input value={email} type="text" id="email" name="email" className="form-control"onChange={(e)=>{setEmail(e.target.value)}}/>
                            <label for="email" className="text-white">Your email</label>
                        </div>
                    </div>
                    

                </div>
                

                
                <div className="row">
                    <div className="col-md-12">
                        <div className="md-form mb-0">
                            <input value={Subject} type="text" id="subject" name="subject" className="form-control"onChange={(e)=>{setSubject(e.target.value)}}/>
                            <label for="subject" className="text-white">Subject</label>
                        </div>
                    </div>
                </div>
                

                
                <div className="row">

                    
                    <div className="col-md-12">

                        <div className="md-form">
                            <textarea value={message} onChange={(e)=>{setMessage(e.target.value)}} type="text" id="message" name="message" rows="2" className="form-control md-textarea"></textarea>
                            <label for="message" className='text-white'>Your message</label>
                        </div>

                    </div>
                </div>
                
             <center><button onClick={send} className='btn btn-primary' >send</button></center>
            </form>

            
   
      
</div>
    </div>

</section> */}

<Footer/>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</>
  )
}

export default Contact