import React, { useState } from 'react'
import Head from 'next/head'
import axios from 'axios';
import Navbar from '@/components/Navbar';

function Contact() {
    const [name,setName] = useState('')
    const [email,setEmail] = useState('')
    const [Subject,setSubject] = useState('')
    const [message,setMessage]= useState('')
    
    const send =async (e)=>{
        e.preventDefault();

        
      
        try {
          await axios.post('/api/mail', { name:name, email:email, message:message ,subject:Subject });
          console.log('Email sent successfully');
          // Reset the form or show a success message to the user
        } catch (error) {
          console.error('Error sending email:', error);
          // Handle and display the error to
      }
    }
  return (
    <>

      <Head>
        <title>Jezh Technologies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous"/>
      </Head>



      <Navbar/>



      <section>


      <div class="container py-3">

    <div class="px-lg-5 py-3  mb-4 bg-body-tertiary rounded-4">
      <div class="container-fluid">
        <div class="row align-items-md-stretch">
        <div class="col-md-8 d-flex align-items-center">
          <div class="">
          <h1 class="display-6 fw-bolder">Contact Us</h1>
        <p class="col-md-8 fs-5 fw-medium">For general queries, sales and partnerships please drop a email anytime and we will reach you.</p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start pt-2">
        <a class="btn bg-black text-white text-start btn-lg rounded-3 me-md-2" href="mailto:info@jezhtechnologies.com">
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-envelope-fill me-2 mb-1" viewBox="0 0 16 16">
  <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757Zm3.436-.586L16 11.801V4.697l-5.803 3.546Z"/>
</svg>
          <span className="fs-5 fw-semibold text-break">info@jezhtechnologies.com</span>
        </a>

          <a class="btn bg-success text-white btn-lg px-4 text-start text-decoration-none" data-action="open" data-phone="919385722102" data-message="Hello, I am interested in your service" href="https://web.whatsapp.com/send?phone=919385722102&amp;text=Hello, I am interested in your service" target="_blank">
          
          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-whatsapp me-2 mb-1" viewBox="0 0 16 16">
  <path d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z"/>
</svg>
            <span className="fs-5 fw-bold text-break text-white">+91-93857 22102</span>
          </a>
        </div>

        
          </div>
        </div>
        <div class="col-md-4">
          <div class="">
            <img className="img-fluid" src="https://uploads-ssl.webflow.com/6450b8115518edb92e39a41a/646f0e4ce7321b061e4a97f0_Contact%20us-cuate-p-800.png" alt="" width="500"/>
          </div>
        </div>
    </div>
      </div>
    </div>

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 bg-white rounded-4">
          <h1 className="fw-bolder">Office Location</h1>
          <p className="fs-4 fw-medium">Have an idea? Let's grab a coffee and make a revolution.</p>
          <address className="fs-4 fw-semibold">
    <strong>JEZH TECHNOLOGIES</strong><br/>
    Sri Sai Complex, Court Road,<br/>
    Vepamoodu Junction, Nagercoil,<br/>
    Kanyakumari, Tamil Nadu,<br/>
    India-629001.<br/>
    <abbr title="Phone">Phone:</abbr> 93857 22102 <br/>
    <abbr title="Phone">Landline:</abbr> 04652-288007

  </address>
          
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-3 bg-body-tertiary border rounded-3 ratio ratio-4x3">
        <iframe className="rounded-4 img-fluid" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d739.8872091509062!2d77.43067399307816!3d8.182330973528224!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3b04f1d9f6f28009%3A0xfbc653de52850d62!2sJabz%20Technologies%20Private%20Limited!5e1!3m2!1sen!2sin!4v1685065256487!5m2!1sen!2sin" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
      </div>
    </div>
  </div>








        {/* <div class="container px-lg-5 my-3 bg-white rounded-5">
    <div class="row align-items-center">
      <div class="col-lg-8">
        <h1 class="display-3 fw-bold text-black">Contact us</h1>
        <div class="badge bg-transparent text-wrap" >
        <p class="text-black lead fs-5 py-2">
For general queries, sales and partnerships please drop a email anytime and we will reach you.
</p>
        </div>


<div class="d-grid gap-2 d-md-flex justify-content-md-start">
<a className="btn btn-dark " href="">E-MAIL US</a>
<a className="btn btn-dark " align="left" href="">
<ul class="list-inline">
  <li class="list-inline-item">
  <span>WHATSAPP US ON</span>
    <br />
    <span>+91-94867 99358</span>
  </li>
  <li class="list-inline-item">
  <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-whatsapp" viewBox="0 0 16 16">
  <path d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z"/>
</svg>
  </li>

</ul>
</a>
        </div>

        
      </div>
      <div class="col-lg-4 p-0">
          <img class="rounded-lg-3 img-fluid" src="https://uploads-ssl.webflow.com/6450b8115518edb92e39a41a/646f0e4ce7321b061e4a97f0_Contact%20us-cuate-p-800.png" alt="" width="500"/>
      </div>
    </div>
  </div> */}




        </section>



{/* <section className="mb-4">


    <h2 className="h1-responsive font-weight-bold text-center my-4">Contact us</h2>

    <p className="text-white text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
        a matter of hours to help you.</p>

    <div className="row">

        
        <div className="col-md-9 mb-md-0 mb-5">
            <form id="contact-form" name="contact-form"  method="POST">

                
                <div className="row">

                    
                    <div className="">
                        <div className="md-form mb-0">
                            <input value={name} type="text" id="name" name="name" className="form-control" onChange={(e)=>{setName(e.target.value)}}/>
                            <label for="name" className="text-white">Your name</label>
                        </div>
                    </div>
                    

                    
                    <div className="">
                        <div className="md-form mb-0">
                            <input value={email} type="text" id="email" name="email" className="form-control"onChange={(e)=>{setEmail(e.target.value)}}/>
                            <label for="email" className="text-white">Your email</label>
                        </div>
                    </div>
                    

                </div>
                

                
                <div className="row">
                    <div className="col-md-12">
                        <div className="md-form mb-0">
                            <input value={Subject} type="text" id="subject" name="subject" className="form-control"onChange={(e)=>{setSubject(e.target.value)}}/>
                            <label for="subject" className="text-white">Subject</label>
                        </div>
                    </div>
                </div>
                

                
                <div className="row">

                    
                    <div className="col-md-12">

                        <div className="md-form">
                            <textarea value={message} onChange={(e)=>{setMessage(e.target.value)}} type="text" id="message" name="message" rows="2" className="form-control md-textarea"></textarea>
                            <label for="message" className='text-white'>Your message</label>
                        </div>

                    </div>
                </div>
                
             <center><button onClick={send} className='btn btn-primary' >send</button></center>
            </form>

            
   
      
</div>
    </div>

</section> */}

<div class="container">
  <footer class="pt-5">
    <div class="row">
      <div class="col-6 col-md-2 mb-3">
        <h6 class="font-monospace border-bottom pb-2 me-3 text-white">Who we are</h6>
        <ul class="nav flex-column">
          <li class="nav-item mb-2">
            <a href="#" class="nav-link p-0 text-white fs-4">
            About Us
            <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="currentColor" class="bi bi-arrow-up-right fw-bolder mb-1 ms-1" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M14 2.5a.5.5 0 0 0-.5-.5h-6a.5.5 0 0 0 0 1h4.793L2.146 13.146a.5.5 0 0 0 .708.708L13 3.707V8.5a.5.5 0 0 0 1 0v-6z"/>
</svg>
            </a>
          </li>
          <li class="nav-item mb-2">
            <a href="#" class="nav-link p-0 text-white fs-4">
            Blogs
            <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="currentColor" class="bi bi-arrow-up-right fw-bolder mb-1 ms-1" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M14 2.5a.5.5 0 0 0-.5-.5h-6a.5.5 0 0 0 0 1h4.793L2.146 13.146a.5.5 0 0 0 .708.708L13 3.707V8.5a.5.5 0 0 0 1 0v-6z"/>
</svg>
            </a>
          </li>
          <li class="nav-item mb-2">
            <a href="#" class="nav-link p-0 text-white fs-4">
            Career
            <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="currentColor" class="bi bi-arrow-up-right fw-bolder mb-1 ms-1" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M14 2.5a.5.5 0 0 0-.5-.5h-6a.5.5 0 0 0 0 1h4.793L2.146 13.146a.5.5 0 0 0 .708.708L13 3.707V8.5a.5.5 0 0 0 1 0v-6z"/>
</svg>
            </a>
          </li>
         
        </ul>
      </div>

      <div class="col-6 col-md-2 mb-3">
        <h6 class="font-monospace border-bottom pb-2 me-3 text-white">Services</h6>
        <ul class="nav flex-column">
          <li class="nav-item mb-2">
            <a href="#" class="nav-link p-0 text-white fs-4">
            Design
            <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="currentColor" class="bi bi-arrow-up-right fw-bolder mb-1 ms-1" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M14 2.5a.5.5 0 0 0-.5-.5h-6a.5.5 0 0 0 0 1h4.793L2.146 13.146a.5.5 0 0 0 .708.708L13 3.707V8.5a.5.5 0 0 0 1 0v-6z"/>
</svg>
          </a>
          </li>
          <li class="nav-item mb-2">
            <a href="#" class="nav-link p-0 text-white fs-4">
            Development
            <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="currentColor" class="bi bi-arrow-up-right fw-bolder mb-1 ms-1" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M14 2.5a.5.5 0 0 0-.5-.5h-6a.5.5 0 0 0 0 1h4.793L2.146 13.146a.5.5 0 0 0 .708.708L13 3.707V8.5a.5.5 0 0 0 1 0v-6z"/>
</svg>
          </a>
          </li>
          <li class="nav-item mb-2">
            <a href="#" class="nav-link p-0 text-white fs-4">
            Marketing
            <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="currentColor" class="bi bi-arrow-up-right fw-bolder mb-1 ms-1" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M14 2.5a.5.5 0 0 0-.5-.5h-6a.5.5 0 0 0 0 1h4.793L2.146 13.146a.5.5 0 0 0 .708.708L13 3.707V8.5a.5.5 0 0 0 1 0v-6z"/>
</svg>
          </a>
          </li>          
        </ul>
      </div>

      {/* <div class="col-6 col-md-2 mb-3">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
        </ul>
      </div> */}

      <div class="col-md-5 offset-md-1 my-5 text-center">
      <form>
          <h4 className="fw-bold text-start ps-2 pb-2 text-white">Subscribe to our newsletter to know what's new and exciting from us.</h4>
          <div class="d-flex flex-column flex-sm-row w-100 gap-2 bg-white rounded-3 border-0">
            <input type="email" class="form-control border-0 shadow-none rounded-pill ps-4 py-3" placeholder="Email address"/>
            <button class="btn btn-white outline-0 border-0 shadow-none text-white fw-bold px-3 m-1 bg-dark rounded-3" type="button">Subscribe</button>
          </div>
        </form>
      </div>
    </div>

    <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
      <p class=" text-white">© 2023 Jezh Technologies Pvt Ltd. All rights reserved.</p>
      <ul class="list-unstyled d-flex">
        <li class="">
          <a class="link-body-emphasis" href="#">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-facebook text-dark bg-white p-1 rounded-circle" viewBox="0 0 16 16">
              <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
            </svg>
          </a>
        </li>
        <li class="ms-3"><a class="link-body-emphasis" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-twitter text-dark bg-white p-1 rounded-circle" viewBox="0 0 16 16">
  <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
</svg></a></li>
        <li class="ms-3">
          <a class="link-body-emphasis" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-instagram text-dark bg-white p-1 rounded-circle" viewBox="0 0 16 16">
  <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
</svg>
          </a>
        </li>
      </ul>
    </div>
  </footer>
</div>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</>
  )
}

export default Contact