import React from 'react'
import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Getproposal from '@/components/Getproposal'

function Development() {
  return (
    <>
          <Head>
        <title>Jezh Technologies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
      
      <main className="px-lg-5 mx-lg-5 px-md-1 text-white ">
        <Navbar/>
        <nav class="text-bg-transparent text-black bg-gradient bg-white rounded rounded-top-0 rounded-bottom-2">
  <ol class="breadcrumb p-3">
    <li class="breadcrumb-item"><a class="text-decoration-none p-1 text-black fw-semibold fs-5" href="#">Home</a></li>
    <li class="breadcrumb-item"><a class="text-decoration-none p-1 text-black fw-semibold fs-5" href="#">Services</a></li>
    <li class="breadcrumb-item active" aria-current="page"><span class="border border-top-0 border-start-0 border-end-0 border-secondary fw-semibold fs-5">Development</span></li>
  </ol>
</nav>
        <section>
        <div class="container my-5">
    <div class="row align-items-center">
      <div class="col-lg-8">
        <h1 class="display-3 fw-bold lh-2 text-white mb-4">Powering Your Future through our Cutting-Edge Technological Solutions</h1>
        <Getproposal/>

        
      </div>
      <div class="col-lg-4 p-0">
          <img class="rounded-lg-3 img-fluid" src="https://uploads-ssl.webflow.com/6450b8115518edb92e39a41a/64b1693d42acb9387334b218_Data%20extraction-amico.png" alt="" width="500"/>
      </div>
    </div>
  </div>
        </section>

        {/* <section>
          <div class="container text-center">
            <h5 class="fw-bold ls-1">We have worked with</h5>
            <img src="https://avk.edu.in/wp-content/uploads/2023/04/Untitled-design-2.png" height="150" width="150" class="img-fluid"/>
            <img/>
            <img src="https://lagoontechnologies.com/wp-content/uploads/2022/05/cropped-favicon-lagoon.png" height="100" width="100" class="img-fluid"/>
          </div>
        </section> */}




   <section>
   <div class="container text-center bg-transparent rounded-4 py-5">
    <h1 class="fw-bolder">Why Choose Us ?</h1>
    <h4 class="fw-normal">We are a bootstrapped company that understands the needs of our clients and helps them grow.

</h4>
  <div class="row pt-4 text-start text-center text-white">
    <div class="col-sm">
      <div class="card text-bg-transparent text-white bg-gradient bg-transparent rounded-4 rounded-bottom-0 border border-bottom-0 border-secondary mb-3">
  
  <div class="card-body ">
    <h3 class="card-title fw-bolder">Expert Solutions</h3>
    <p class="card-text fs-5">Delivering cutting-edge software solutions tailored to your needs. Our experienced team ensures high-quality results.</p>
  </div>
</div>
    </div>
    <div class="col-sm">
      <div class="card text-bg-transparent text-white bg-gradient bg-transparent rounded-4 rounded-bottom-0 border border-bottom-0 border-secondary mb-3">
  
  <div class="card-body ">
    <h3 class="card-title fw-bolder">Seamless Integration</h3>
    <p class="card-text fs-5">Effortless integration with your existing systems. Streamline operations and boost efficiency with our software services.</p>
  </div>
</div>
    </div>
    <div class="col-sm">
      <div class="card text-bg-transparent text-white bg-gradient bg-transparent rounded-4 rounded-bottom-0 border border-bottom-0 border-secondary mb-3">
  
  <div class="card-body ">
    <h3 class="card-title fw-bolder">Customer Focus</h3>
    <p class="card-text fs-5">Putting you first. We prioritize your satisfaction with excellent support and personalized solutions..</p>
  </div>
</div>
    </div>
  </div>
</div>
   </section>


   <section class="py-4">
   <div class="container text-center py-5">
    <h1 class="fw-bolder mb-3"><a>Software</a> services we provide</h1>
    <h4 class="fw-normal"> Unlock the potential of great design with our tailored services. Elevate your brand, engage your audience, and achieve lasting success with our design solutions.</h4>

    <div class="container text-start text-bg-transparent bg-gradient bg-transparent border border-secondary rounded-4 mt-5 p-3">
  <div class="row">
    <div class="col-sm">
            <div class="card text-white bg-transparent border-0 rounded-0 mb-3">
  
  <div class="card-body">
  <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-window-split text-white mb-2" viewBox="0 0 16 16">
  <path d="M2.5 4a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1Zm2-.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0Zm1 .5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1Z"/>
  <path d="M2 1a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2H2Zm12 1a1 1 0 0 1 1 1v2H1V3a1 1 0 0 1 1-1h12ZM1 13V6h6.5v8H2a1 1 0 0 1-1-1Zm7.5 1V6H15v7a1 1 0 0 1-1 1H8.5Z"/>
</svg>
    <h3 class="card-title fw-bolder">Web Development</h3>
    <p class="card-text fs-5"> Experience the power of seamless collaboration with our design experts. Choose us for efficient teamwork and flawless execution.</p>
  </div>
</div>
    </div><div class="vr p-0"></div>

    <div class="col-sm">
            <div class="card text-white bg-transparent border-0 rounded-0 mb-3">
  
  <div class="card-body mb-0 pb-0">
  <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-tablet text-white mb-2" viewBox="0 0 16 16">
  <path d="M12 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h8zM4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4z"/>
  <path d="M8 14a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
</svg>
    <h3 class="card-title fw-bolder">App Development</h3>
    <p class="card-text fs-5"> Experience the power of seamless collaboration with our design experts. Choose us for efficient teamwork and flawless execution.</p>
  </div>
</div>
    </div><div class="vr p-0"></div>
    
    <div class="col-sm">
            <div class="card text-white bg-transparent border-0 rounded-0 mb-3">
  
  <div class="card-body">
  <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-terminal text-white mb-2" viewBox="0 0 16 16">
  <path d="M6 9a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1h-3A.5.5 0 0 1 6 9zM3.854 4.146a.5.5 0 1 0-.708.708L4.793 6.5 3.146 8.146a.5.5 0 1 0 .708.708l2-2a.5.5 0 0 0 0-.708l-2-2z"/>
  <path d="M2 1a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2H2zm12 1a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h12z"/>
</svg>
    <h3 class="card-title fw-bolder">Software Development</h3>
    <p class="card-text fs-5"> Experience the power of seamless collaboration with our design experts. Choose us for efficient teamwork and flawless execution.</p>
  </div>
</div>
    </div>
  </div>
  <hr/>
  <div class="row ">
    <div class="col-sm">
            <div class="card text-white bg-transparent border-0 rounded-0 mb-3">
  
  <div class="card-body ">
  <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-cart4 text-white mb-2" viewBox="0 0 16 16">
  <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
</svg>
    <h3 class="card-title fw-bolder">E-Commerce Development</h3>
    <p class="card-text fs-5"> Experience the power of seamless collaboration with our design experts. Choose us for efficient teamwork and flawless execution.</p>
  </div>
</div>
    </div><div class="vr p-0"></div>
    <div class="col-sm">
            <div class="card text-white bg-transparent border-0 rounded-0 mb-3">
  
  <div class="card-body ">
  <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-cpu text-white mb-2" viewBox="0 0 16 16">
  <path d="M5 0a.5.5 0 0 1 .5.5V2h1V.5a.5.5 0 0 1 1 0V2h1V.5a.5.5 0 0 1 1 0V2h1V.5a.5.5 0 0 1 1 0V2A2.5 2.5 0 0 1 14 4.5h1.5a.5.5 0 0 1 0 1H14v1h1.5a.5.5 0 0 1 0 1H14v1h1.5a.5.5 0 0 1 0 1H14v1h1.5a.5.5 0 0 1 0 1H14a2.5 2.5 0 0 1-2.5 2.5v1.5a.5.5 0 0 1-1 0V14h-1v1.5a.5.5 0 0 1-1 0V14h-1v1.5a.5.5 0 0 1-1 0V14h-1v1.5a.5.5 0 0 1-1 0V14A2.5 2.5 0 0 1 2 11.5H.5a.5.5 0 0 1 0-1H2v-1H.5a.5.5 0 0 1 0-1H2v-1H.5a.5.5 0 0 1 0-1H2v-1H.5a.5.5 0 0 1 0-1H2A2.5 2.5 0 0 1 4.5 2V.5A.5.5 0 0 1 5 0zm-.5 3A1.5 1.5 0 0 0 3 4.5v7A1.5 1.5 0 0 0 4.5 13h7a1.5 1.5 0 0 0 1.5-1.5v-7A1.5 1.5 0 0 0 11.5 3h-7zM5 6.5A1.5 1.5 0 0 1 6.5 5h3A1.5 1.5 0 0 1 11 6.5v3A1.5 1.5 0 0 1 9.5 11h-3A1.5 1.5 0 0 1 5 9.5v-3zM6.5 6a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"/>
</svg>
    <h3 class="card-title fw-bolder">AI & IoT Development</h3>
    <p class="card-text fs-5"> Experience the power of seamless collaboration with our design experts. Choose us for efficient teamwork and flawless execution.</p>
  </div>
</div>
    </div><div class="vr p-0"></div>
    <div class="col-sm">
            <div class="card text-white bg-transparent border-0 rounded-0 mb-3">
  
  <div class="card-body ">
  <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-hdd-stack text-white mb-2" viewBox="0 0 16 16">
  <path d="M14 10a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1v-1a1 1 0 0 1 1-1h12zM2 9a2 2 0 0 0-2 2v1a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-1a2 2 0 0 0-2-2H2z"/>
  <path d="M5 11.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm-2 0a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zM14 3a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h12zM2 2a2 2 0 0 0-2 2v1a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H2z"/>
  <path d="M5 4.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm-2 0a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"/>
</svg>
    <h3 class="card-title fw-bolder">Hosting</h3>
    <p class="card-text fs-5"> Experience the power of seamless collaboration with our design experts. Choose us for efficient teamwork and flawless execution.</p>
  </div>
</div>
    </div>
  </div>
</div>

</div>
   </section>






        <section>
        <div class="container my-5">
  <div class="p-5 text-center bg-body-tertiary rounded-4 mx-auto text-center">
    <h1 class="text-dark fw-bolder">Download our company’s corporate profile and get to know more about us and what we do!</h1>
    <p></p>
    <p class="lead text-center">


    <div class="d-flex justify-content-center">
        <ul class="list-inline">
        <a class="btn btn-dark btn-lg rounded-3 pe-2 fw-medium" href="#">
        <li class="list-inline-item">
  <div class="p-1 w-100">
  <span className="">Download Brochure
</span> 
  </div>
  </li>
  <li class="list-inline-item">
  <div class="p-2 flex-shrink-1">

          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-download text-white" viewBox="0 0 16 16">
  <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
  <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
</svg>
  </div>
  </li>
  </a>
  </ul>
</div>

    </p>
  </div>
</div>
        </section>
        <Footer/>
      </main>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    </>
  )
}

export default Development