import React from 'react'
import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Getproposal from '@/components/Getproposal'

function Marketing() {
  return (
    <>
          <Head>
        <title>Jezh Technologies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
      
      <main className="px-lg-5 mx-lg-5 px-md-1 text-white ">
        <Navbar/>
<nav class="text-bg-transparent text-black bg-gradient bg-white rounded rounded-top-0 rounded-bottom-2">
  <ol class="breadcrumb p-3">
    <li class="breadcrumb-item"><a class="text-decoration-none p-1 text-black fw-semibold fs-5" href="#">Home</a></li>
    <li class="breadcrumb-item"><a class="text-decoration-none p-1 text-black fw-semibold fs-5" href="#">Services</a></li>
    <li class="breadcrumb-item active" aria-current="page"><span class="border border-top-0 border-start-0 border-end-0 border-secondary fw-bolder fs-5">Marketing</span></li>
  </ol>
</nav>
        <section>
        <div class="container my-5">
    <div class="row align-items-center">
      <div class="col-lg-8">
        <h1 class="display-3 fw-bold lh-2 text-white mb-4">Amplify Your Business Success with Our Strategic Marketing Solutions</h1>
        <Getproposal/>

        
      </div>
      <div class="col-lg-4 p-0">
          <img class="rounded-lg-3 img-fluid" src="https://uploads-ssl.webflow.com/6450b8115518edb92e39a41a/64b1775bfd335e702a326838_Marketing%20consulting-rafiki%20(1).png" alt="" width="500"/>
      </div>
    </div>
  </div>
        </section>

        {/* <section>
          <div class="container text-center">
            <h5 class="fw-bold ls-1">We have worked with</h5>
            <img src="https://avk.edu.in/wp-content/uploads/2023/04/Untitled-design-2.png" height="150" width="150" class="img-fluid"/>
            <img/>
            <img src="https://lagoontechnologies.com/wp-content/uploads/2022/05/cropped-favicon-lagoon.png" height="100" width="100" class="img-fluid"/>
          </div>
        </section> */}




   <section>
   <div class="container text-center bg-transparent rounded-4 py-5">
    <h1 class="fw-bolder">Why Choose Us ?</h1>
    <h4 class="fw-normal">We are a bootstrapped company that understands the needs of our clients and helps them grow.

</h4>
  <div class="row pt-4 text-start text-center text-white">
    <div class="col-sm">
      <div class="card text-bg-transparent text-white bg-gradient bg-transparent rounded-4 rounded-bottom-0 border border-bottom-0 border-secondary mb-3">
  
  <div class="card-body ">
    <h3 class="card-title fw-bolder">Amplify Your Reach</h3>
    <p class="card-text fs-5"> Expand your brand's reach with our digital mastery. Boost visibility and engage your audience effectively.</p>
  </div>
</div>
    </div>
    <div class="col-sm">
      <div class="card text-bg-transparent text-white bg-gradient bg-transparent rounded-4 rounded-bottom-0 border border-bottom-0 border-secondary mb-3">
  
  <div class="card-body ">
    <h3 class="card-title fw-bolder">Unleash Your Potential</h3>
    <p class="card-text fs-5">Ignite growth with our marketing expertise. Maximize your brand's potential and achieve remarkable success.</p>
  </div>
</div>
    </div>
    <div class="col-sm">
      <div class="card text-bg-transparent text-white bg-gradient bg-transparent rounded-4 rounded-bottom-0 border border-bottom-0 border-secondary mb-3">
  
  <div class="card-body ">
    <h3 class="card-title fw-bolder">Embrace Transformation</h3>
    <p class="card-text fs-5">Embrace change and elevate your brand to new heights. Experience transformative marketing strategies for lasting impact.</p>
  </div>
</div>
    </div>
  </div>
</div>
   </section>


   <section class="py-4">
   <div class="container text-center py-5">
    <h1 class="fw-bolder mb-3">Design services we provide</h1>
    <h4 class="fw-normal"> Unlock the potential of great design with our tailored services. Elevate your brand, engage your audience, and achieve lasting success with our design solutions.</h4>

    <div class="container text-center text-bg-transparent bg-gradient bg-transparent border border-secondary rounded-4 text-center mt-5 p-3">
  <div class="row">
    <div class="col-sm">
            <div class="card text-white bg-transparent border-0 rounded-0 mb-3">
  
  <div class="card-body">
    <h3 class="card-title fw-bolder">Web Designing</h3>
    <p class="card-text fs-5"> Experience the power of seamless collaboration with our design experts. Choose us for efficient teamwork and flawless execution.</p>
  </div>
</div>
    </div><div class="vr p-0"></div>

    <div class="col-sm">
            <div class="card text-white bg-transparent border-0 rounded-0 mb-3">
  
  <div class="card-body mb-0 pb-0">
    <h3 class="card-title fw-bolder">Ui / Ux designing</h3>
    <p class="card-text fs-5"> Experience the power of seamless collaboration with our design experts. Choose us for efficient teamwork and flawless execution.</p>
  </div>
</div>
    </div><div class="vr p-0"></div>
    
    <div class="col-sm">
            <div class="card text-white bg-transparent border-0 rounded-0 mb-3">
  
  <div class="card-body">
    <h3 class="card-title fw-bolder"> Poster Designing</h3>
    <p class="card-text fs-5"> Experience the power of seamless collaboration with our design experts. Choose us for efficient teamwork and flawless execution.</p>
  </div>
</div>
    </div>
  </div>
  <hr/>
  <div class="row ">
    <div class="col-sm">
            <div class="card text-white bg-transparent border-0 rounded-0 mb-3">
  
  <div class="card-body ">
    <h3 class="card-title fw-bolder">Seamless Collaboration</h3>
    <p class="card-text fs-5"> Experience the power of seamless collaboration with our design experts. Choose us for efficient teamwork and flawless execution.</p>
  </div>
</div>
    </div><div class="vr p-0"></div>
    <div class="col-sm">
            <div class="card text-white bg-transparent border-0 rounded-0 mb-3">
  
  <div class="card-body ">
    <h3 class="card-title fw-bolder">Seamless Collaboration</h3>
    <p class="card-text fs-5"> Experience the power of seamless collaboration with our design experts. Choose us for efficient teamwork and flawless execution.</p>
  </div>
</div>
    </div><div class="vr p-0"></div>
    <div class="col-sm">
            <div class="card text-white bg-transparent border-0 rounded-0 mb-3">
  
  <div class="card-body ">
    <h3 class="card-title fw-bolder">Seamless Collaboration</h3>
    <p class="card-text fs-5"> Experience the power of seamless collaboration with our design experts. Choose us for efficient teamwork and flawless execution.</p>
  </div>
</div>
    </div>
  </div>
</div>

</div>
   </section>






        <section>
        <div class="container my-5">
  <div class="p-5 text-center bg-body-tertiary rounded-4 mx-auto text-center">
    <h1 class="text-dark fw-bolder">Download our company’s corporate profile and get to know more about us and what we do!</h1>
    <p></p>
    <p class="lead text-center">


    <div class="d-flex justify-content-center">
        <ul class="list-inline">
        <a class="btn btn-dark btn-lg rounded-3 pe-2 fw-medium" href="#">
        <li class="list-inline-item">
  <div class="p-1 w-100">
  <span className="">Download Brochure
</span> 
  </div>
  </li>
  <li class="list-inline-item">
  <div class="p-2 flex-shrink-1">

          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-download text-white" viewBox="0 0 16 16">
  <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
  <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
</svg>
  </div>
  </li>
  </a>
  </ul>
</div>

    </p>
  </div>
</div>
        </section>
        <Footer/>
      </main>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    </>
  )
}

export default Marketing